services:
  - type: web
    name: hardware-query-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory: $(pwd)"
      echo "Listing files:"
      ls -la
      echo "Copying hardware_data.xlsx..."
      cp hardware_data.xlsx /opt/render/project/src/
      echo "Verifying copy:"
      ls -la /opt/render/project/src/hardware_data.xlsx
      mkdir -p /opt/render/project/src/logs
      chmod 777 /opt/render/project/src/logs
      chmod +x startup.sh
    startCommand: |
      python create_db.py
      echo "Database created, checking tables..."
      python - <<EOF
      import sqlite3
      conn = sqlite3.connect('hardware.db')
      cursor = conn.cursor()
      cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
      tables = cursor.fetchall()
      print("Tables in database:", [table[0] for table in tables])
      for table in tables:
          cursor.execute(f"PRAGMA table_info({table[0]})")
          columns = cursor.fetchall()
          print(f"\nTable {table[0]} columns:")
          for col in columns:
              print(f"  {col[1]} ({col[2]})")
      conn.close()
      EOF
      gunicorn app:app 2>&1 | tee -a /opt/render/project/src/logs/gunicorn.log
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: .
    assets:
      - path: /opt/render/project/src/hardware.xlsx
        source: C:/Users/Admin-Frankie/Desktop/hardware.xlsx
