services:
  - type: web
    name: hardware-query-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_application.wsgi:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONPATH
        value: .
