version: "1"
services:
  - type: web
    name: hardware-query-app
    runtime: python
    repo: https://github.com/frankpedersen84/hardware-query-app
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && chmod +x prestart.sh
    startCommand: bash -c 'source $GUNICORN_CMD_ARGS="--config gunicorn.conf.py" && exec gunicorn wsgi:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
