services:
  - type: web
    name: hardware-query-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x prestart.sh
    startCommand: |
      ./prestart.sh
      gunicorn app:app --bind 0.0.0.0:$PORT --log-file /var/log/gunicorn.log --access-logfile /var/log/access.log --error-logfile /var/log/error.log --capture-output --enable-stdio-inheritance
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    healthCheckPath: /
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - hardware_data.xlsx
        - prestart.sh
