version: "1"
services:
  - type: web
    name: hardware-query-app
    runtime: python
    repo: https://github.com/frankpedersen84/hardware-query-app
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && chmod +x prestart.sh
    startCommand: ./prestart.sh && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - hardware_data.xlsx
        - prestart.sh
