services:
  - type: web
    name: hardware-query-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:application
    envVars:
      - key: OPENAI_API_KEY
        sync: false
